title: ArnovskyCG
bio: Motion Designer 2D/3D
url: https://arnovskyCG.github.io
logo: assets/img/logo.png # ton logo si tu en as
background: assets/img/bg.jpg # facultatif
twitter: ton_twitter_handle # facultatif
locale: en_US
permalink: /:title/
